version: '3.8'

services:
  opensearch-node1:
    image: docker.io/opensearchproject/opensearch:2.12.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-demo-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      # Set memory lock to false
      - bootstrap.memory_lock=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Djdk.tls.client.protocols=TLSv1.2"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Ag4skH8KV8mxee7n5XouNNd2ooA5JC
    # Remove or comment out the ulimits.memlock section if bootstrap.memory_lock=false
    ulimits:
      # memlock:  # <-- Commented out or removed
      #   soft: -1
      #   hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net: